import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { MapPin, Search, Scale } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import QuoteModal from '../../components/recycler/QuoteModal';
import { lotApi } from '../../services/lotApi';
import { Badge, Button, Card, EmptyState, LoadingState, PageHeader } from '../../components/ui/Primitives';
import type { MaterialLot } from '../../types/models';

export default function RecyclerDashboard() {
  const { t } = useTranslation(); const [selectedLot, setSelectedLot] = useState<MaterialLot | null>(null); const [search, setSearch] = useState(''); const [condition, setCondition] = useState('ALL');
  const lotsQuery = useQuery({ queryKey: ['availableLots'], queryFn: () => lotApi.getAvailableLots() }); const lots: MaterialLot[] = useMemo(() => lotsQuery.data?.data || [], [lotsQuery.data]);
  const filteredLots = useMemo(() => lots.filter((lot) => { const value = `${lot.material_category_name || ''} ${lot.material_description || ''} ${lot.collection_location || ''}`.toLowerCase(); return (!search || value.includes(search.toLowerCase())) && (condition === 'ALL' || String(lot.condition || '').toUpperCase() === condition); }), [lots, search, condition]);
  return <><PageHeader title={t('marketplace.title')} description={t('marketplace.description')} /><section className="marketplace-toolbar" aria-label={t('marketplace.searchLabel')}><label className="search-wrap"><Search size={16} aria-hidden="true" /><input className="search-field" value={search} onChange={(event) => setSearch(event.target.value)} placeholder={t('marketplace.searchPlaceholder')} aria-label={t('marketplace.searchLabel')} /></label><select className="filter-select" value={condition} onChange={(event) => setCondition(event.target.value)} aria-label={t('marketplace.conditionFilter')}><option value="ALL">{t('marketplace.allConditions')}</option><option value="WORKING">{t('createLot.working')}</option><option value="REPAIRABLE">{t('createLot.repairable')}</option><option value="SCRAP">{t('createLot.scrap')}</option><option value="MIXED">{t('createLot.mixed')}</option></select></section>{lotsQuery.isLoading ? <LoadingState label={t('marketplace.findingLots')} /> : lotsQuery.isError ? <div className="error-state"><strong>{t('marketplace.unavailableTitle')}</strong><p>{t('marketplace.unavailableDescription')}</p><Button variant="secondary" onClick={() => void lotsQuery.refetch()}>{t('common.tryAgain')}</Button></div> : filteredLots.length === 0 ? <EmptyState title={t(lots.length === 0 ? 'marketplace.noLotsTitle' : 'marketplace.noMatchesTitle')} description={t(lots.length === 0 ? 'marketplace.noLotsDescription' : 'marketplace.noMatchesDescription')} /> : <section className="marketplace-grid" aria-label={t('marketplace.title')}>{filteredLots.map((lot) => <Card className="market-card" as="article" key={lot.id}><div className="market-image-wrap">{lot.images?.[0] ? <img className="market-card-image" src={lot.images[0]} alt={`${lot.material_category_name || t('common.eWaste')} ${t('common.lot')}`} /> : <div className="market-card-image lot-placeholder">{t('common.noImage')}</div>}<span className="market-image-status"><Badge tone="success">{t('marketplace.available')}</Badge></span></div><div className="market-card-body"><p className="eyebrow">{t('common.lot')}</p><h2>{lot.material_category_name || t('common.uncategorised')}</h2><div className="market-card-meta"><span><Scale size={14} /> {t('quotes.lotSummary', { weight: lot.approximate_weight ?? lot.weight_kg, unit: lot.weight_unit || t('common.kg'), condition: '' }).replace(' · ', '')}</span><span><MapPin size={14} /> {lot.collection_location || t('common.locationPending')}</span><span>{t('marketplace.condition', { value: lot.condition || t('common.conditionNotSpecified') })}</span></div><Button variant="secondary" className="full-button" onClick={() => setSelectedLot(lot)}>{t('marketplace.viewAndQuote')}</Button></div></Card>)}</section>}{selectedLot && <QuoteModal lot={selectedLot} onClose={() => setSelectedLot(null)} />}</>;
}
